/**
 * Custom routes for the Review API.
 *
 * `/reviews/import-published` is the WordPress migration target — Full-Access
 * API tokens can POST a complete review payload and have it stored as
 * published in one round-trip. Filename starts with `01-` so it loads before
 * the core route generated by `routes/review.ts`.
 */

export default {
  routes: [
    {
      method: 'POST',
      path: '/reviews/import-published',
      handler: 'api::review.review.importPublished',
      config: {
        // No `policies` / `middlewares` — auth is handled by Strapi's standard
        // API-token guard. Public role does NOT get this permission, so only
        // Full-Access tokens can reach it.
        policies: [],
        middlewares: [],
      },
    },
  ],
};
